# Generated by Django 3.0.8 on 2020-08-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200817_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
