# Generated by Django 3.0.8 on 2020-08-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200731_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
